package main

import (
  "encoding/json"
  "log"
  "net/http"
  "github.com/gorilla/mux"
  "fmt"
  // "io/ioutil"
  // "reflect"
)


type Users struct {
  Id string `json:"id"`
  SlackName string `json:"slackName"`
  Name string `json:"name"`
  Url string `json:"url"`
}

var name string = "all"

func GetUsers(w http.ResponseWriter, r *http.Request) {
  params := mux.Vars(r)
  name = params["name"]
  fmt.Println(name)
  jsonData := `
    [
    {
      "id": "1",
      "slackName": "Ben Cooke",
      "name": "Ben Cooke",
      "url": "ben.cooke"
    },
    {
      "id": "2",
      "slackName": "ben.hackett",
      "name": "Ben Hackett",
      "url": "ben.hackett"
    },
    {
      "id": "3",
      "slackName": "blaise",
      "name": "Blaise Calaycay",
      "url": "blaise.calaycay"
    },
    {
      "id": "4",
      "slackName": "jamesn",
      "name": "James Nicolas",
      "url": "james.nicolas"
    }
    ]
  `
  var users []map[string]interface{}
  err := json.Unmarshal([]byte(jsonData), &users)
  if err != nil {
    log.Fatal(err)
  }
  w.Header().Set("Content-Type", "application/json")
  json.NewEncoder(w).Encode(users)

}

func GetUser(w http.ResponseWriter, r *http.Request) {
  params := mux.Vars(r)
  name = params["name"]

  repos := GetUserRepos(name)
  languages := GetLanguages(repos)

  userData := make(map[string]interface{})

  userData["id"] = 1
  userData["slackName"] = "Ben Cooke"
  userData["name"] = "Ben Cooke"
  userData["url"] = "ben.cooke"
  userData["github"] = "https://github.com/BenCookie95"
  userData["gitlab"] = ""
  userData["languages"] = languages
  userData["repos"] = repos

  // jsonData := `
  //   {
  //     "id": "1",
  //     "slackName": "Ben Cooke",
  //     "name": "Ben Cooke",
  //     "url": "ben.cooke",
  //     "github": "https://github.com/bencookie95",
  //     "gitlab": "",
  //     "languages": ["Java"],
  //     "repos": [
  //       {
  //         "name": "AndroidRestService",
  //         "link": "https://github.com/BenCookie95/AndroidRestService",
  //         "languages": ["Java"]
  //       },
  //       {
  //         "name": "Blackjack",
  //         "link": "https://github.com/BenCookie95/Blackjack",
  //         "languages": ["Java"]
  //       }
  //     ]
  //   }
  // `

  // var user map[string]interface{}
  // err := json.Unmarshal([]byte(jsonData), &user)
  // if err != nil {
  //   log.Fatal(err)
  // }
  w.Header().Set("Content-Type", "application/json")
  json.NewEncoder(w).Encode(userData)

}

func GetLanguages(repos []map[string]interface{}) map[string]int {
    allLanguages := make(map[string]int)

    for iRepo:= range repos {
      repo := repos[iRepo]
      languages := repo["languages"].([]string)
      // fmt.Println(reflect.TypeOf(languages))
      for iLanguage := 0; iLanguage < len(languages); iLanguage++ {
        language := languages[iLanguage]
        if val, ok := allLanguages[language]; ok {
          allLanguages[language] = val + 1
        } else {
          allLanguages[language] = 1
        }
      }
    }

    return allLanguages
}


func GetUserRepos(user string)  []map[string]interface{} {
  /*
  Format of repos

  "repos": [
    {
      "name": "AndroidRestService",
      "link": "https://github.com/BenCookie95/AndroidRestService",
      "languages": ["Java"]
    },
    {
      "name": "Blackjack",
      "link": "https://github.com/BenCookie95/Blackjack",
      "languages": ["Java"]
    }
  ]
  */
  // var client http.Client

  var repos []map[string]interface{}

  // resp, err := client.Get("https://api.github.com/users/bencookie95/repos")
  // if err != nil {
  //
  // }
  // defer resp.Body.Close()
  //
  // jsonData, err := ioutil.ReadAll(resp.Body)

  jsonData := `
  [
  {
    "id": 55295937,
    "name": "AndroidRestService",
    "full_name": "BenCookie95/AndroidRestService",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/AndroidRestService",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/AndroidRestService",
    "forks_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/AndroidRestService/deployments",
    "created_at": "2016-04-02T13:29:03Z",
    "updated_at": "2016-04-02T13:54:11Z",
    "pushed_at": "2016-09-23T11:37:16Z",
    "git_url": "git://github.com/BenCookie95/AndroidRestService.git",
    "ssh_url": "git@github.com:BenCookie95/AndroidRestService.git",
    "clone_url": "https://github.com/BenCookie95/AndroidRestService.git",
    "svn_url": "https://github.com/BenCookie95/AndroidRestService",
    "homepage": null,
    "size": 5072,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 43243462,
    "name": "Blackjack",
    "full_name": "BenCookie95/Blackjack",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/Blackjack",
    "description": "A text based game of blackjack built with Java in Netbeans",
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/Blackjack",
    "forks_url": "https://api.github.com/repos/BenCookie95/Blackjack/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/Blackjack/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/Blackjack/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/Blackjack/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/Blackjack/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/Blackjack/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/Blackjack/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/Blackjack/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/Blackjack/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/Blackjack/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/Blackjack/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/Blackjack/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/Blackjack/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/Blackjack/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/Blackjack/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/Blackjack/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/Blackjack/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/Blackjack/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/Blackjack/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/Blackjack/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/Blackjack/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/Blackjack/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/Blackjack/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/Blackjack/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/Blackjack/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/Blackjack/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/Blackjack/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/Blackjack/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/Blackjack/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/Blackjack/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/Blackjack/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/Blackjack/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/Blackjack/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/Blackjack/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/Blackjack/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/Blackjack/deployments",
    "created_at": "2015-09-27T11:04:34Z",
    "updated_at": "2015-09-27T11:04:49Z",
    "pushed_at": "2015-09-27T15:11:59Z",
    "git_url": "git://github.com/BenCookie95/Blackjack.git",
    "ssh_url": "git@github.com:BenCookie95/Blackjack.git",
    "clone_url": "https://github.com/BenCookie95/Blackjack.git",
    "svn_url": "https://github.com/BenCookie95/Blackjack",
    "homepage": null,
    "size": 164,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 96520236,
    "name": "ckeditor-dev",
    "full_name": "BenCookie95/ckeditor-dev",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/ckeditor-dev",
    "description": "The development repository of CKEditor.",
    "fork": true,
    "url": "https://api.github.com/repos/BenCookie95/ckeditor-dev",
    "forks_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/ckeditor-dev/deployments",
    "created_at": "2017-07-07T09:01:28Z",
    "updated_at": "2017-07-07T09:01:41Z",
    "pushed_at": "2017-07-06T14:41:54Z",
    "git_url": "git://github.com/BenCookie95/ckeditor-dev.git",
    "ssh_url": "git@github.com:BenCookie95/ckeditor-dev.git",
    "clone_url": "https://github.com/BenCookie95/ckeditor-dev.git",
    "svn_url": "https://github.com/BenCookie95/ckeditor-dev",
    "homepage": "http://ckeditor.com",
    "size": 46402,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 88505089,
    "name": "fantasy-footy",
    "full_name": "BenCookie95/fantasy-footy",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/fantasy-footy",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/fantasy-footy",
    "forks_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/fantasy-footy/deployments",
    "created_at": "2017-04-17T12:16:26Z",
    "updated_at": "2017-04-17T12:16:26Z",
    "pushed_at": "2017-04-17T12:19:40Z",
    "git_url": "git://github.com/BenCookie95/fantasy-footy.git",
    "ssh_url": "git@github.com:BenCookie95/fantasy-footy.git",
    "clone_url": "https://github.com/BenCookie95/fantasy-footy.git",
    "svn_url": "https://github.com/BenCookie95/fantasy-footy",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 86828811,
    "name": "FutBackend",
    "full_name": "BenCookie95/FutBackend",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/FutBackend",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/FutBackend",
    "forks_url": "https://api.github.com/repos/BenCookie95/FutBackend/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/FutBackend/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/FutBackend/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/FutBackend/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/FutBackend/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/FutBackend/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/FutBackend/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/FutBackend/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/FutBackend/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/FutBackend/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/FutBackend/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/FutBackend/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/FutBackend/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/FutBackend/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/FutBackend/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/FutBackend/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/FutBackend/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/FutBackend/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/FutBackend/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/FutBackend/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/FutBackend/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/FutBackend/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/FutBackend/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/FutBackend/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/FutBackend/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/FutBackend/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/FutBackend/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/FutBackend/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/FutBackend/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/FutBackend/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/FutBackend/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/FutBackend/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/FutBackend/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/FutBackend/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/FutBackend/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/FutBackend/deployments",
    "created_at": "2017-03-31T14:36:27Z",
    "updated_at": "2017-03-31T14:41:39Z",
    "pushed_at": "2017-03-31T14:41:37Z",
    "git_url": "git://github.com/BenCookie95/FutBackend.git",
    "ssh_url": "git@github.com:BenCookie95/FutBackend.git",
    "clone_url": "https://github.com/BenCookie95/FutBackend.git",
    "svn_url": "https://github.com/BenCookie95/FutBackend",
    "homepage": null,
    "size": 2613,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 86829426,
    "name": "FutFrontend",
    "full_name": "BenCookie95/FutFrontend",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/FutFrontend",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/FutFrontend",
    "forks_url": "https://api.github.com/repos/BenCookie95/FutFrontend/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/FutFrontend/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/FutFrontend/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/FutFrontend/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/FutFrontend/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/FutFrontend/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/FutFrontend/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/FutFrontend/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/FutFrontend/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/FutFrontend/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/FutFrontend/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/FutFrontend/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/FutFrontend/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/FutFrontend/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/FutFrontend/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/FutFrontend/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/FutFrontend/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/FutFrontend/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/FutFrontend/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/FutFrontend/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/FutFrontend/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/FutFrontend/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/FutFrontend/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/FutFrontend/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/FutFrontend/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/FutFrontend/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/FutFrontend/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/FutFrontend/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/FutFrontend/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/FutFrontend/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/FutFrontend/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/FutFrontend/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/FutFrontend/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/FutFrontend/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/FutFrontend/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/FutFrontend/deployments",
    "created_at": "2017-03-31T14:42:23Z",
    "updated_at": "2017-03-31T14:43:44Z",
    "pushed_at": "2017-03-31T14:43:43Z",
    "git_url": "git://github.com/BenCookie95/FutFrontend.git",
    "ssh_url": "git@github.com:BenCookie95/FutFrontend.git",
    "clone_url": "https://github.com/BenCookie95/FutFrontend.git",
    "svn_url": "https://github.com/BenCookie95/FutFrontend",
    "homepage": null,
    "size": 147,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 75402360,
    "name": "GigForMe",
    "full_name": "BenCookie95/GigForMe",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/GigForMe",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/GigForMe",
    "forks_url": "https://api.github.com/repos/BenCookie95/GigForMe/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/GigForMe/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/GigForMe/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/GigForMe/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/GigForMe/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/GigForMe/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/GigForMe/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/GigForMe/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/GigForMe/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/GigForMe/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/GigForMe/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/GigForMe/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/GigForMe/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/GigForMe/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/GigForMe/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/GigForMe/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/GigForMe/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/GigForMe/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/GigForMe/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/GigForMe/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/GigForMe/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/GigForMe/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/GigForMe/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/GigForMe/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/GigForMe/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/GigForMe/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/GigForMe/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/GigForMe/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/GigForMe/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/GigForMe/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/GigForMe/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/GigForMe/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/GigForMe/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/GigForMe/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/GigForMe/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/GigForMe/deployments",
    "created_at": "2016-12-02T14:26:37Z",
    "updated_at": "2016-12-02T14:37:07Z",
    "pushed_at": "2016-12-02T14:38:57Z",
    "git_url": "git://github.com/BenCookie95/GigForMe.git",
    "ssh_url": "git@github.com:BenCookie95/GigForMe.git",
    "clone_url": "https://github.com/BenCookie95/GigForMe.git",
    "svn_url": "https://github.com/BenCookie95/GigForMe",
    "homepage": null,
    "size": 15647,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 65246961,
    "name": "JWT_JAX-RS",
    "full_name": "BenCookie95/JWT_JAX-RS",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/JWT_JAX-RS",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS",
    "forks_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/JWT_JAX-RS/deployments",
    "created_at": "2016-08-08T23:29:17Z",
    "updated_at": "2016-08-08T23:37:02Z",
    "pushed_at": "2016-08-09T02:09:09Z",
    "git_url": "git://github.com/BenCookie95/JWT_JAX-RS.git",
    "ssh_url": "git@github.com:BenCookie95/JWT_JAX-RS.git",
    "clone_url": "https://github.com/BenCookie95/JWT_JAX-RS.git",
    "svn_url": "https://github.com/BenCookie95/JWT_JAX-RS",
    "homepage": null,
    "size": 10203,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 94013428,
    "name": "Online-Store",
    "full_name": "BenCookie95/Online-Store",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/Online-Store",
    "description": "Online store built with Laravel (Still in progress)",
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/Online-Store",
    "forks_url": "https://api.github.com/repos/BenCookie95/Online-Store/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/Online-Store/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/Online-Store/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/Online-Store/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/Online-Store/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/Online-Store/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/Online-Store/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/Online-Store/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/Online-Store/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/Online-Store/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/Online-Store/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/Online-Store/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/Online-Store/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/Online-Store/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/Online-Store/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/Online-Store/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/Online-Store/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/Online-Store/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/Online-Store/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/Online-Store/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/Online-Store/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/Online-Store/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/Online-Store/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/Online-Store/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/Online-Store/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/Online-Store/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/Online-Store/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/Online-Store/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/Online-Store/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/Online-Store/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/Online-Store/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/Online-Store/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/Online-Store/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/Online-Store/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/Online-Store/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/Online-Store/deployments",
    "created_at": "2017-06-11T15:25:02Z",
    "updated_at": "2017-06-11T15:27:29Z",
    "pushed_at": "2017-09-22T02:55:37Z",
    "git_url": "git://github.com/BenCookie95/Online-Store.git",
    "ssh_url": "git@github.com:BenCookie95/Online-Store.git",
    "clone_url": "https://github.com/BenCookie95/Online-Store.git",
    "svn_url": "https://github.com/BenCookie95/Online-Store",
    "homepage": null,
    "size": 5233,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "PHP",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 46667792,
    "name": "ReminderApp",
    "full_name": "BenCookie95/ReminderApp",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/ReminderApp",
    "description": "This is my first android project, I'm looking to create a simple reminder app using an sqlite database",
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/ReminderApp",
    "forks_url": "https://api.github.com/repos/BenCookie95/ReminderApp/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/ReminderApp/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/ReminderApp/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/ReminderApp/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/ReminderApp/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/ReminderApp/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/ReminderApp/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/ReminderApp/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/ReminderApp/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/ReminderApp/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/ReminderApp/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/ReminderApp/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/ReminderApp/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/ReminderApp/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/ReminderApp/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/ReminderApp/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/ReminderApp/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/ReminderApp/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/ReminderApp/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/ReminderApp/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/ReminderApp/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/ReminderApp/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/ReminderApp/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/ReminderApp/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/ReminderApp/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/ReminderApp/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/ReminderApp/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/ReminderApp/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/ReminderApp/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/ReminderApp/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/ReminderApp/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/ReminderApp/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/ReminderApp/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/ReminderApp/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/ReminderApp/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/ReminderApp/deployments",
    "created_at": "2015-11-22T16:02:03Z",
    "updated_at": "2015-11-22T16:02:18Z",
    "pushed_at": "2015-11-22T16:02:17Z",
    "git_url": "git://github.com/BenCookie95/ReminderApp.git",
    "ssh_url": "git@github.com:BenCookie95/ReminderApp.git",
    "clone_url": "https://github.com/BenCookie95/ReminderApp.git",
    "svn_url": "https://github.com/BenCookie95/ReminderApp",
    "homepage": null,
    "size": 74,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 42545430,
    "name": "Restaurant-Order-System",
    "full_name": "BenCookie95/Restaurant-Order-System",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/Restaurant-Order-System",
    "description": "This is a college project where we were tasked with creating an order system for a restaurant using java in the netbeans IDE.  Our solution incorporates an embedded derby database to store the orders and food menu.",
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System",
    "forks_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/Restaurant-Order-System/deployments",
    "created_at": "2015-09-15T20:43:25Z",
    "updated_at": "2017-03-21T18:38:19Z",
    "pushed_at": "2015-09-27T11:12:37Z",
    "git_url": "git://github.com/BenCookie95/Restaurant-Order-System.git",
    "ssh_url": "git@github.com:BenCookie95/Restaurant-Order-System.git",
    "clone_url": "https://github.com/BenCookie95/Restaurant-Order-System.git",
    "svn_url": "https://github.com/BenCookie95/Restaurant-Order-System",
    "homepage": null,
    "size": 3056,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "master"
  },
  {
    "id": 55303483,
    "name": "YikSnap",
    "full_name": "BenCookie95/YikSnap",
    "owner": {
      "login": "BenCookie95",
      "id": 14115924,
      "avatar_url": "https://avatars0.githubusercontent.com/u/14115924?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/BenCookie95",
      "html_url": "https://github.com/BenCookie95",
      "followers_url": "https://api.github.com/users/BenCookie95/followers",
      "following_url": "https://api.github.com/users/BenCookie95/following{/other_user}",
      "gists_url": "https://api.github.com/users/BenCookie95/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/BenCookie95/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/BenCookie95/subscriptions",
      "organizations_url": "https://api.github.com/users/BenCookie95/orgs",
      "repos_url": "https://api.github.com/users/BenCookie95/repos",
      "events_url": "https://api.github.com/users/BenCookie95/events{/privacy}",
      "received_events_url": "https://api.github.com/users/BenCookie95/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/BenCookie95/YikSnap",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/BenCookie95/YikSnap",
    "forks_url": "https://api.github.com/repos/BenCookie95/YikSnap/forks",
    "keys_url": "https://api.github.com/repos/BenCookie95/YikSnap/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/BenCookie95/YikSnap/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/BenCookie95/YikSnap/teams",
    "hooks_url": "https://api.github.com/repos/BenCookie95/YikSnap/hooks",
    "issue_events_url": "https://api.github.com/repos/BenCookie95/YikSnap/issues/events{/number}",
    "events_url": "https://api.github.com/repos/BenCookie95/YikSnap/events",
    "assignees_url": "https://api.github.com/repos/BenCookie95/YikSnap/assignees{/user}",
    "branches_url": "https://api.github.com/repos/BenCookie95/YikSnap/branches{/branch}",
    "tags_url": "https://api.github.com/repos/BenCookie95/YikSnap/tags",
    "blobs_url": "https://api.github.com/repos/BenCookie95/YikSnap/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/BenCookie95/YikSnap/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/BenCookie95/YikSnap/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/BenCookie95/YikSnap/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/BenCookie95/YikSnap/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/BenCookie95/YikSnap/languages",
    "stargazers_url": "https://api.github.com/repos/BenCookie95/YikSnap/stargazers",
    "contributors_url": "https://api.github.com/repos/BenCookie95/YikSnap/contributors",
    "subscribers_url": "https://api.github.com/repos/BenCookie95/YikSnap/subscribers",
    "subscription_url": "https://api.github.com/repos/BenCookie95/YikSnap/subscription",
    "commits_url": "https://api.github.com/repos/BenCookie95/YikSnap/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/BenCookie95/YikSnap/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/BenCookie95/YikSnap/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/BenCookie95/YikSnap/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/BenCookie95/YikSnap/contents/{+path}",
    "compare_url": "https://api.github.com/repos/BenCookie95/YikSnap/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/BenCookie95/YikSnap/merges",
    "archive_url": "https://api.github.com/repos/BenCookie95/YikSnap/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/BenCookie95/YikSnap/downloads",
    "issues_url": "https://api.github.com/repos/BenCookie95/YikSnap/issues{/number}",
    "pulls_url": "https://api.github.com/repos/BenCookie95/YikSnap/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/BenCookie95/YikSnap/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/BenCookie95/YikSnap/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/BenCookie95/YikSnap/labels{/name}",
    "releases_url": "https://api.github.com/repos/BenCookie95/YikSnap/releases{/id}",
    "deployments_url": "https://api.github.com/repos/BenCookie95/YikSnap/deployments",
    "created_at": "2016-04-02T16:06:37Z",
    "updated_at": "2016-04-02T16:12:41Z",
    "pushed_at": "2016-04-17T18:37:19Z",
    "git_url": "git://github.com/BenCookie95/YikSnap.git",
    "ssh_url": "git@github.com:BenCookie95/YikSnap.git",
    "clone_url": "https://github.com/BenCookie95/YikSnap.git",
    "svn_url": "https://github.com/BenCookie95/YikSnap",
    "homepage": null,
    "size": 597,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
]

  `

  json.Unmarshal([]byte(jsonData), &repos)
  // repos now has repos data from github for the specified user

  newRepos := make([]map[string]interface{}, 0)

  for i := range repos {
      repoData := make(map[string]interface{})
      repo := repos[i]

      repoData["name"] = repo["name"]
      repoData["link"] = "https://github.com/" + repo["full_name"].(string)

      // populate languages

      //var languages []map[string]int
      // var client http.Client
      // resp, err := client.Get(repo["languages_url"].(string))
      // if err != nil {
      //
      // }
      // defer resp.Body.Close()
      // jsonLanguageData, err := ioutil.ReadAll(resp.Body)
      // json.Unmarshal(jsonLanguageData, &languages)
      // repoData["languages"] = languages

      languageSizeMap := map[string]int{"Java": 123, "PHP": 132, "Swift": 10}
      languages := make([]string, 0)
      for language, _ := range languageSizeMap {
        languages = append(languages, language)
      }
      repoData["languages"] = languages

      newRepos = append(newRepos, repoData)
  }
  return newRepos

}

func main() {
  router := mux.NewRouter()
  // fmt.Println(GetUserRepos("ben")[0])
  // GetUserRepos("ben")
  // fmt.Println(GetLanguages(GetUserRepos("ben")))
  router.HandleFunc("/users/{name}", GetUsers).Methods("GET")
  router.HandleFunc("/user/{name}", GetUser).Methods("GET")
  log.Println("Listening on port 8000")
  log.Fatal(http.ListenAndServe(":8000", router))
}
